name: codacy coverage reporter
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
      - codacy-dev
    paths-ignore:
      - '.github/workflows/*'
  #push:
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: pull repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run test with coverage
        run: |
          coverage run -m unittest discover
          coverage report -m
          coverage xml
      - name: upload code coverage report to codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml